
import React, { useState } from 'react';
// FIX: Imported Variants from framer-motion to correctly type animation variants.
import { motion, AnimatePresence, Variants } from 'framer-motion';
import type { Project } from '../types';
import { ChevronLeftIcon, ChevronRightIcon } from './icons';

const projectsData: Project[] = [
  { id: 1, title: 'E-Commerce Brix', category: 'web', image: 'https://www.vocso.com/blog/wp-content/uploads/2022/02/eCommerce-Website-Features-1920-x-1080.jpg', description: 'A modern e-commerce platform with a blocky, minimalist design, focusing on a seamless user experience and secure payment processing.', techStack: ['Next.js', 'Tailwind CSS', 'Stripe', 'MongoDB'], liveUrl: 'https://example.com', repoUrl: 'https://github.com' },
  { id: 2, title: 'Pixel Portfolio', category: 'web', image: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?q=80&w=800&h=600&auto=format&fit=crop', description: 'A dynamic portfolio website for a digital artist, featuring fluid animations and a content management system for easy updates.', techStack: ['React', 'Framer Motion', 'Contentful'], liveUrl: 'https://example.com' },
  { id: 3, title: 'Data Dash', category: 'web', image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&h=600&auto=format&fit=crop', description: 'An interactive data visualization dashboard for a tech startup, providing real-time insights with a clean and intuitive interface.', techStack: ['React', 'D3.js', 'Firebase'], liveUrl: 'https://example.com', repoUrl: 'https://github.com' },
  { 
    id: 4, 
    title: 'Visual Branding Suite', 
    category: 'design', 
    image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=800&h=600&auto=format&fit=crop', 
    images: [
      'https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=800&h=600&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?q=80&w=800&h=600&auto=format&fit=crop',
      'https://graphicdesignjunction.com/wp-content/uploads/2023/12/brand_visual_identity_logo_examples-870x567.jpg'
    ],
    description: 'A collection of thumbnails, posters, and social media graphics for various clients, showcasing a strong eye for design and brand consistency.', 
    techStack: ['Photoshop', 'Illustrator', 'Figma'] 
  },
  { id: 5, title: 'University Web Portal', category: 'academic', image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=800&h=600&auto=format&fit=crop', description: 'A comprehensive final year project featuring a multi-functional portal for students and faculty with role-based access and features.', techStack: ['React', 'Node.js', 'MongoDB', 'JWT'], repoUrl: 'https://github.com' },
  {
    id: 6,
    title: 'Authenticated PDF Generator',
    category: 'academic',
    image: 'https://images.unsplash.com/photo-1599658880436-c61792e70672?q=80&w=800&h=600&auto=format&fit=crop',
    description: 'A secure system for generating and verifying authenticated PDF documents, ideal for certificates and official records. Built as a final year project.',
    techStack: ['Node.js', 'Express', 'MongoDB', 'JWT', 'pdf-lib'],
    repoUrl: 'https://github.com'
  },
  {
    id: 7,
    title: 'Movie Recommendation System',
    category: 'academic',
    image: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=800&h=600&auto=format&fit=crop',
    description: 'A machine learning-powered recommendation engine that suggests movies to users based on their viewing history and preferences.',
    techStack: ['Python', 'Flask', 'scikit-learn', 'Pandas', 'React'],
    repoUrl: 'https://github.com'
  },
  {
    id: 8,
    title: 'Thumbnail & Poster Design',
    category: 'design',
    image: 'https://s3-alpha.figma.com/hub/file/2183079306710579270/d97e01aa-0bd7-4298-a1b5-4c984c87e3d3-cover.png',
    images: [ 
      'https://s3-alpha.figma.com/hub/file/2183079306710579270/d97e01aa-0bd7-4298-a1b5-4c984c87e3d3-cover.png',
      'https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=800&h=600&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1534970028765-38ce47ef7d8d?q=80&w=800&h=600&auto=format&fit=crop'
    ],
    description: 'Eye-catching thumbnails and posters for social media, events, and marketing campaigns. We design visuals that grab attention and drive clicks.',
    techStack: ['Photoshop', 'Illustrator', 'Canva', 'Figma']
  },
  {
    id: 9,
    title: 'Run Chase: Gemini-Powered Game',
    category: 'game',
    image: 'https://wallpaperaccess.com/full/2604895.jpg',
    description: 'An exciting cricket arcade game where you chase high scores. Featuring real-time, dynamic commentary generated by the Gemini Live API for an immersive and interactive experience.',
    techStack: ['React', 'Three.js', 'Framer Motion', '@google/genai'],
    liveUrl: 'https://example.com',
    repoUrl: 'https://github.com'
  },
];

const categories = ['all', 'web', 'design', 'academic', 'game'];

const ProjectCard: React.FC<{ project: Project; onClick: () => void }> = ({ project, onClick }) => {
  return (
    <motion.div
      layout
      initial={{ opacity: 0, scale: 0.8 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.8 }}
      transition={{ duration: 0.4, ease: 'easeInOut' }}
      className="rounded-lg shadow-lg overflow-hidden cursor-pointer group"
      onClick={onClick}
      whileHover={{ y: -8, boxShadow: '0 10px 20px rgba(0,0,0,0.1), 0 6px 6px rgba(0,0,0,0.1)' }}
    >
      <div className="relative h-64">
        <img src={project.image} alt={project.title} className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110" />
        <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent transition-all duration-300 group-hover:from-black/80" />
        <div className="absolute bottom-0 left-0 right-0 p-4">
          <h3 className="text-white text-2xl font-heading font-bold drop-shadow-md">{project.title}</h3>
          <p className="text-primary font-bold uppercase text-sm drop-shadow-md">{project.category}</p>
        </div>
        <div className="absolute inset-0 bg-black/50 backdrop-blur-[2px] flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <div className="flex items-center gap-2 text-white text-lg font-bold">
                <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" /></svg>
                <span>View Project</span>
            </div>
        </div>
      </div>
    </motion.div>
  );
};

const imageVariants: Variants = {
    enter: (direction: number) => ({
        x: direction > 0 ? 300 : -300,
        opacity: 0,
    }),
    center: {
        zIndex: 1,
        x: 0,
        opacity: 1,
    },
    exit: (direction: number) => ({
        zIndex: 0,
        x: direction < 0 ? 300 : -300,
        opacity: 0,
    }),
};

const ProjectModal: React.FC<{ project: Project; closeModal: () => void }> = ({ project, closeModal }) => {
    const [[imageIndex, direction], setImageState] = useState([0, 0]);
    const images = project.images && project.images.length > 0 ? project.images : [project.image];
    
    const paginate = (newDirection: number) => {
        const newIndex = (imageIndex + newDirection + images.length) % images.length;
        setImageState([newIndex, newDirection]);
    };

    const handleThumbnailClick = (index: number) => {
        setImageState([index, index > imageIndex ? 1 : -1]);
    };

    return (
        <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4"
            onClick={closeModal}
        >
            <motion.div
                initial={{ scale: 0.9, y: 30 }}
                animate={{ scale: 1, y: 0 }}
                exit={{ scale: 0.9, y: 30 }}
                transition={{ duration: 0.3, ease: 'easeInOut' }}
                className="bg-light-bg dark:bg-dark-bg w-full max-w-4xl rounded-lg shadow-2xl relative overflow-hidden max-h-[90vh] flex flex-col"
                onClick={(e) => e.stopPropagation()}
            >
                <div className="p-4 sm:p-6 flex-shrink-0 flex justify-between items-center border-b border-light-gray dark:border-dark-gray">
                    <h3 className="text-2xl sm:text-3xl font-heading font-bold">{project.title}</h3>
                    <button onClick={closeModal} className="text-3xl leading-none z-10 p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors">&times;</button>
                </div>
                
                <div className="flex-grow overflow-y-auto">
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 p-4 sm:p-6">
                        <div>
                            <div className="relative aspect-video rounded-lg overflow-hidden mb-4 shadow-md group">
                                <AnimatePresence initial={false} custom={direction}>
                                    <motion.img
                                        key={imageIndex}
                                        src={images[imageIndex]}
                                        alt={`${project.title} - view ${imageIndex + 1}`}
                                        className="absolute inset-0 w-full h-full object-cover"
                                        custom={direction}
                                        variants={imageVariants}
                                        initial="enter"
                                        animate="center"
                                        exit="exit"
                                        transition={{ x: { type: "spring", stiffness: 300, damping: 30 }, opacity: { duration: 0.2 } }}
                                    />
                                </AnimatePresence>
                                {images.length > 1 && (
                                    <>
                                        <button onClick={() => paginate(-1)} className="absolute left-2 top-1/2 -translate-y-1/2 z-10 text-white bg-black/30 p-2 rounded-full hover:bg-black/50 transition-colors opacity-0 group-hover:opacity-100"><ChevronLeftIcon /></button>
                                        <button onClick={() => paginate(1)} className="absolute right-2 top-1/2 -translate-y-1/2 z-10 text-white bg-black/30 p-2 rounded-full hover:bg-black/50 transition-colors opacity-0 group-hover:opacity-100"><ChevronRightIcon /></button>
                                    </>
                                )}
                            </div>
                            {images.length > 1 && (
                                <div className="flex gap-2 justify-center">
                                    {images.map((img, index) => (
                                        <button 
                                            key={index}
                                            onClick={() => handleThumbnailClick(index)}
                                            className={`w-16 h-12 rounded-md overflow-hidden border-2 transition-all duration-300 ${imageIndex === index ? 'border-primary scale-110' : 'border-transparent hover:border-primary/50'}`}
                                        >
                                            <img src={img} alt={`thumbnail ${index + 1}`} className="w-full h-full object-cover" />
                                        </button>
                                    ))}
                                </div>
                            )}
                        </div>
                        
                        <div>
                            <p className="text-lg mb-6">{project.description}</p>
                            <h4 className="font-bold text-xl mb-3">Tech Stack</h4>
                            <div className="flex flex-wrap gap-2 mb-6">
                                {project.techStack.map(tech => (
                                    <span key={tech} className="bg-primary/20 text-primary font-medium px-3 py-1 text-sm rounded-full">{tech}</span>
                                ))}
                            </div>
                            <div className="flex flex-wrap gap-4">
                                {project.liveUrl && (
                                    <a 
                                        href={project.liveUrl} 
                                        target="_blank" 
                                        rel="noopener noreferrer" 
                                        className="inline-flex items-center gap-2 bg-primary text-white font-bold px-6 py-2 rounded-md shadow-md hover:bg-primary/90 transition-all duration-300 hover:scale-105"
                                    >
                                        <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" /></svg>
                                        Live Site
                                    </a>
                                )}
                                {project.repoUrl && (
                                    <a 
                                        href={project.repoUrl} 
                                        target="_blank" 
                                        rel="noopener noreferrer" 
                                        className="inline-flex items-center gap-2 bg-gray-700 text-white font-bold px-6 py-2 rounded-md shadow-md hover:bg-gray-600 transition-all duration-300 hover:scale-105 dark:bg-gray-800 dark:hover:bg-gray-700"
                                    >
                                        <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path fillRule="evenodd" d="M12 2C6.477 2 2 6.477 2 12c0 4.418 2.865 8.168 6.839 9.492.5.092.682-.217.682-.483 0-.237-.009-.868-.014-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.031-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.203 2.398.1 2.651.64.7 1.03 1.595 1.03 2.688 0 3.848-2.338 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.001 10.001 0 0022 12c0-5.523-4.477-10-10-10z" clipRule="evenodd" /></svg>
                                        View Code
                                    </a>
                                )}
                            </div>
                        </div>
                    </div>
                </div>
            </motion.div>
        </motion.div>
    );
};

const Projects = () => {
  const [filter, setFilter] = useState('all');
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);

  const filteredProjects = filter === 'all'
    ? projectsData
    : projectsData.filter(p => p.category === filter);

  return (
    <section id="projects" className="py-20 bg-light-gray dark:bg-dark-gray">
      <div className="container mx-auto px-4">
        <h2 className="text-5xl font-heading font-bold text-center mb-12">Our Projects</h2>
        <div className="flex justify-center flex-wrap gap-2 sm:gap-4 mb-8">
          {categories.map(category => (
            <button
              key={category}
              onClick={() => setFilter(category)}
              className={`font-heading font-bold text-sm sm:text-base px-4 py-2 sm:px-6 sm:py-2 rounded-full uppercase transition-all duration-300 ${filter === category ? 'bg-primary text-white shadow-md' : 'bg-light-bg dark:bg-dark-bg hover:bg-primary/10'}`}
            >
              {category}
            </button>
          ))}
        </div>
        <motion.div layout className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          <AnimatePresence>
            {filteredProjects.map(project => (
              <ProjectCard key={project.id} project={project} onClick={() => setSelectedProject(project)} />
            ))}
          </AnimatePresence>
        </motion.div>
      </div>
      <AnimatePresence>
        {selectedProject && <ProjectModal project={selectedProject} closeModal={() => setSelectedProject(null)} />}
      </AnimatePresence>
    </section>
  );
};

export default Projects;